//! Invented equipment catalog for a fictional facility: machine types,
//! failure modes and planned-maintenance procedures.
//!
//! Each failure mode carries two vocabularies on purpose: `symptoms` is how
//! the record was written up, `asks` is how someone later asks about it. They
//! overlap only partially, as they do in real logs, so retrieval is not a
//! string-equality exercise.

pub struct Mode {
    pub key: &'static str,
    pub problem: &'static str,
    pub cause: &'static str,
    pub action: &'static str,
    pub symptoms: &'static [&'static str],
    pub asks: &'static [&'static str],
    pub fixes: &'static [&'static str],
    pub steps: &'static [&'static str],
    pub parts: &'static [(&'static str, &'static str)],
}

pub struct Plan {
    pub id: &'static str,
    pub name: &'static str,
    pub steps: &'static [&'static str],
}

pub struct MachineType {
    pub code: &'static str,
    pub name: &'static str,
    pub weight: u32,
    pub modes: &'static [Mode],
    pub plans: &'static [Plan],
}

macro_rules! mode {
    ($key:expr, $p:expr, $c:expr, $a:expr, sym[$($s:expr),*], ask[$($q:expr),*], fix[$($f:expr),*], step[$($t:expr),*], part[$($pt:expr),*]) => {
        Mode { key: $key, problem: $p, cause: $c, action: $a, symptoms: &[$($s),*], asks: &[$($q),*], fixes: &[$($f),*], steps: &[$($t),*], parts: &[$($pt),*] }
    };
}

/// Failure modes any powered machine can have.
pub const GENERIC: &[Mode] = &[
    mode!("motor-overload", "Motor trip", "Overload / overheating", "Reset and corrected load",
        sym["Main motor tripping on overload every 20-30 min", "Motor hot to the touch, overload relay tripped on {side}", "Motor faulting out on overcurrent during startup"],
        ask["motor keeps tripping overload", "motor overheating and kicking out", "overcurrent trip on main motor"],
        fix["Motor fan cover packed with dust; cleaned, checked amps at 11.2A vs 12.5 FLA, ran 2 hrs no trip", "Overload set too low after motor swap; set to nameplate FLA and verified amp draw on all three legs", "Bearing dragging on motor, replaced motor with stocked spare, megger tested OK"],
        step["Lockout / tagout applied", "Check amp draw all 3 legs", "Clean motor cooling fins and fan cover", "Megger motor windings", "Verify overload setting vs nameplate"],
        part[("MTR-5HP-1800", "Motor 5HP 1800RPM TEFC"), ("OL-RLY-12A", "Overload relay 9-13A")]),
    mode!("vfd-fault", "Drive fault", "VFD fault / parameter loss", "Reset / replaced drive",
        sym["VFD showing fault F{f} and unit will not restart", "Drive fault on {side} section, display shows OC", "Inverter tripped on DC bus overvoltage during decel"],
        ask["vfd fault code wont reset", "drive faulted overvoltage on stop", "inverter fault unit down"],
        fix["DC bus overvoltage on decel; increased decel time from 2s to 5s and enabled bus regulator, no further trips", "Drive cooling fan seized causing overtemp; replaced fan, cleaned heatsink", "Replaced VFD with stocked spare, loaded parameter backup, tested all speeds"],
        step["Record fault history from drive", "Check incoming voltage", "Inspect drive cooling fan", "Load parameter backup", "Test run at all speeds"],
        part[("VFD-FAN-80", "Drive cooling fan 80mm"), ("VFD-7.5HP", "VFD 7.5HP 480V")]),
    mode!("sensor-fail", "Sensor fault", "Failed / misaligned sensor", "Replaced / realigned sensor",
        sym["Photo eye at {side} not seeing parts, false faults", "Prox sensor PX{n} intermittent, unit stops randomly", "Position sensor flickering, faults on missing part"],
        ask["photo eye not detecting", "prox sensor intermittent random stops", "false fault from sensor"],
        fix["Reflector for photo eye PE{n} cracked and misaligned; replaced reflector and re-taught sensor", "Prox PX{n} cable chafed at cable track; replaced sensor and cable, re-routed with protection", "Sensor lens coated with residue, cleaned and set sensitivity, added to weekly clean list"],
        step["Check sensor LED status", "Clean sensor lens", "Re-teach / align sensor", "Inspect cable and connector", "Test cycle"],
        part[("SNS-PE-RR", "Photo eye retro-reflective M18"), ("SNS-PX-M12", "Inductive prox M12 PNP")]),
    mode!("air-leak", "Air leak", "Leaking fitting / cylinder seal", "Replaced fitting / seals",
        sym["Loud air leak at {side} manifold", "Cylinder C{n} slow to extend, hissing at rod end", "Air pressure dropping to 60 psi when unit cycles"],
        ask["air leak hissing at cylinder", "pneumatic cylinder slow weak", "low air pressure when cycling"],
        fix["Cylinder C{n} rod seal worn, installed seal kit and adjusted cushions", "Push-to-connect fitting cracked at valve bank; replaced fitting and 2 ft of 3/8 tubing", "Regulator diaphragm leaking, replaced regulator and set 80 psi"],
        step["Soap test fittings", "Check regulator setting", "Replace tubing as needed", "Cycle cylinder and verify speed"],
        part[("PNU-SKIT-40", "Cylinder seal kit 40mm bore"), ("PNU-FIT-38", "Push-to-connect 3/8 elbow")]),
    mode!("estop-circuit", "Safety circuit fault", "Guard switch / E-stop fault", "Replaced safety device",
        sym["Safety relay will not reset, guard shows closed", "E-stop circuit open, cannot reset unit", "Guard interlock on {side} door faulting intermittently"],
        ask["safety relay wont reset", "estop circuit open can't reset", "guard door interlock fault"],
        fix["Interlock switch on {side} door misaligned from hinge sag; adjusted hinge and replaced switch actuator", "E-stop contact block loose on button {n}; replaced contact block and tested full safety circuit", "Safety relay failed internal test; replaced relay and verified dual channel"],
        step["Verify each E-stop and guard in circuit", "Check safety relay diagnostics", "Adjust guard door alignment", "Full safety circuit function test"],
        part[("SAF-RLY-24", "Safety relay 24VDC dual channel"), ("SAF-INT-KEY", "Guard interlock coded actuator")]),
    mode!("bearing-noise", "Noise / vibration", "Bearing / gearbox wear", "Replaced bearing / gearbox",
        sym["Grinding noise from gearbox on {side}", "High vibration on drive end, getting worse", "Squealing bearing noise at main shaft"],
        ask["grinding noise from gearbox", "bearing squealing", "high vibration drive end"],
        fix["Main shaft bearing failed, replaced both pillow block bearings and aligned shaft", "Gearbox oil low and milky; drained, flushed, refilled with ISO 220, scheduled oil analysis", "Gear reducer worn, replaced reducer with stocked spare and realigned coupling"],
        step["Check oil level and condition", "Vibration reading on bearings", "Replace bearings", "Laser align coupling"],
        part[("BRG-UCP-207", "Pillow block bearing UCP207"), ("GBX-RED-20", "Gear reducer 20:1")]),
    mode!("controls-comms", "Controls fault", "Network / comms loss", "Restored communication",
        sym["Touchscreen lost communication with controller, screens frozen", "Network fault on remote IO block {n}", "Unit stopped with comm fault to drive"],
        ask["screen lost comms with controller", "remote io comm fault", "network fault unit stopped"],
        fix["Network cable to IO block {n} crushed in cable tray; replaced cable and added strain relief", "Unmanaged switch in panel failed; replaced with spare switch, all nodes back", "Touchscreen application corrupted; reloaded from backup, verified tags"],
        step["Check link lights on switch", "Ping IO nodes", "Replace patch cable", "Reload screen backup"],
        part[("NET-CAT6-10", "Cat6 industrial cable 10ft"), ("NET-SW-8P", "Industrial switch 8 port")]),
];

pub const TYPES: &[MachineType] = &[
    MachineType {
        code: "AHU",
        name: "Air Handler",
        weight: 8,
        modes: &[
            mode!("ahu-belt", "No airflow", "Fan belt slipping / broken", "Replaced belts",
                sym["Supply fan running but low airflow, belt squeal", "Fan belt broken, no air to zone {n}", "Burning rubber smell from air handler fan section"],
                ask["air handler low airflow belt", "fan belt squealing", "no air to zone"],
                fix["Both fan belts glazed and loose; replaced matched set and tensioned to spec", "Sheave worn causing belt slip; replaced motor sheave and belts, aligned with laser", "Belt broke from misalignment; realigned motor base and installed new belts"],
                step["Lockout fan motor", "Inspect belts and sheaves", "Check sheave alignment", "Tension belts", "Measure airflow"],
                part[("AHU-BLT-B56", "V-belt B56 matched set"), ("AHU-SHV-2B", "Motor sheave 2-groove")]),
            mode!("ahu-filter", "High static pressure", "Filters loaded", "Changed filters",
                sym["Filter differential pressure alarm on air handler", "Zone {n} stuffy, high static across filters", "Dust blowing from supply diffusers"],
                ask["filter pressure alarm air handler", "high static filters", "dust from diffusers"],
                fix["Pre-filters and bag filters fully loaded; replaced all, pressure drop back to 0.4 in wc", "Filter rack seal gap let dust bypass; replaced filters and resealed rack"],
                step["Record filter pressure drop", "Replace pre-filters", "Replace final filters", "Check rack seals"],
                part[("AHU-FLT-24", "Pleated filter 24x24x2"), ("AHU-BAG-24", "Bag filter 24x24 MERV 14")]),
            mode!("ahu-coil-freeze", "Freeze stat trip", "Coil freeze / valve stuck", "Repaired valve",
                sym["Freeze stat tripped on air handler, unit off", "Cooling coil iced over, water on floor"],
                ask["freeze stat trip air handler", "coil iced up"],
                fix["Chilled water valve actuator stuck open; replaced actuator and recalibrated", "Outside air damper stuck open in cold weather; replaced damper linkage"],
                step["Check coil condition", "Stroke chilled water valve", "Check outside air damper", "Reset freeze stat"],
                part[("AHU-ACT-24", "Valve actuator 24V modulating")]),
        ],
        plans: &[Plan {
            id: "PLN-AHU-Q",
            name: "Air handler quarterly service",
            steps: &[
                "Lockout fan motor",
                "Replace filters",
                "Inspect belts and sheaves",
                "Grease fan bearings",
                "Clean drain pan",
                "Check damper operation",
                "Restore power and verify airflow",
            ],
        }],
    },
    MachineType {
        code: "CT",
        name: "Cooling Tower",
        weight: 4,
        modes: &[
            mode!("ct-fan-vibration", "Vibration trip", "Fan blade / gearbox issue", "Rebalanced fan",
                sym["Cooling tower fan tripping on vibration switch", "Tower fan noisy and shaking at full speed"],
                ask["cooling tower fan vibration trip", "tower fan shaking"],
                fix["One fan blade pitch off by 3 degrees; reset all blade pitches and rebalanced", "Gearbox output bearing worn; replaced tower gearbox"],
                step["Lockout fan", "Check blade pitch", "Inspect gearbox oil", "Reset vibration switch"],
                part[("CT-GBX-15", "Tower fan gearbox"), ("CT-VSW", "Vibration cutout switch")]),
            mode!("ct-water-level", "Low basin level", "Makeup valve fault", "Repaired makeup valve",
                sym["Cooling tower basin low level alarm", "Tower overflowing to drain constantly"],
                ask["cooling tower low water", "tower overflowing"],
                fix["Makeup float valve stuck; replaced float and valve seat", "Level sensor fouled with scale; cleaned and recalibrated"],
                step["Check basin level", "Inspect makeup valve", "Clean level sensor"],
                part[("CT-FLT-VLV", "Makeup float valve 1in")]),
        ],
        plans: &[Plan {
            id: "PLN-CT-M",
            name: "Cooling tower monthly service",
            steps: &[
                "Lockout fan",
                "Inspect fill and drift eliminators",
                "Check gearbox oil",
                "Clean basin strainer",
                "Verify chemical feed",
                "Test run",
            ],
        }],
    },
    MachineType {
        code: "CMP",
        name: "Air Compressor",
        weight: 5,
        modes: &[
            mode!("cmp-overheat", "High temperature", "Cooler fouled / low oil", "Cleaned cooler",
                sym["Compressor shut down on high discharge temperature", "Compressor running hot, temp alarm at 105C"],
                ask["compressor high temp shutdown", "air compressor overheating"],
                fix["Aftercooler fins packed with dust; cleaned cooler, temp back to 82C", "Oil level low from a leaking fitting; repaired fitting and topped off oil"],
                step["Check oil level", "Clean cooler", "Check thermal valve", "Run and log temps"],
                part[("CMP-OIL-5G", "Compressor oil 5 gal"), ("CMP-TV", "Thermal valve element")]),
            mode!("cmp-pressure", "Low system pressure", "Inlet valve / leaks", "Repaired inlet valve",
                sym["Shop air pressure dropping below 85 psi", "Compressor loading constantly, never reaches cut-out"],
                ask["low shop air pressure", "compressor not building pressure"],
                fix["Inlet valve diaphragm torn; replaced diaphragm kit", "Major leak at drain valve; replaced auto drain"],
                step["Check inlet valve", "Leak survey", "Check auto drains"],
                part[("CMP-IVK", "Inlet valve kit"), ("CMP-DRN", "Zero-loss drain")]),
        ],
        plans: &[Plan {
            id: "PLN-CMP-M",
            name: "Compressor monthly service",
            steps: &[
                "Check oil level",
                "Replace inlet filter",
                "Clean cooler",
                "Test auto drains",
                "Log running hours",
            ],
        }],
    },
    MachineType {
        code: "CRN",
        name: "Overhead Crane",
        weight: 3,
        modes: &[
            mode!("crn-hoist-brake", "Hoist drift", "Brake worn", "Adjusted / replaced brake",
                sym["Crane hoist drifts down with load", "Hoist brake slipping, load creeps"],
                ask["crane hoist drifting", "hoist brake slipping"],
                fix["Hoist brake lining worn below limit; replaced brake and adjusted air gap", "Brake rectifier failed; replaced rectifier"],
                step["Lockout crane", "Measure brake air gap", "Replace brake lining", "Load test"],
                part[("CRN-BRK", "Hoist brake assembly"), ("CRN-RECT", "Brake rectifier")]),
            mode!("crn-pendant", "No travel", "Pendant / contactor fault", "Replaced pendant",
                sym["Crane will not travel east, hoist works", "Pendant button {n} intermittent"],
                ask["crane wont travel", "pendant button not working"],
                fix["Pendant cable broken internally; replaced pendant and cable", "Travel contactor contacts burnt; replaced contactor"],
                step["Check pendant buttons", "Check contactors", "Function test all motions"],
                part[("CRN-PND-6", "Pendant 6-button"), ("CRN-CTR", "Travel contactor")]),
        ],
        plans: &[Plan {
            id: "PLN-CRN-A",
            name: "Crane annual inspection",
            steps: &[
                "Lockout crane",
                "Inspect wire rope",
                "Inspect hook and latch",
                "Check brake",
                "Check limit switches",
                "Load test",
            ],
        }],
    },
    MachineType {
        code: "IMM",
        name: "Injection Molder",
        weight: 7,
        modes: &[
            mode!("imm-heater", "Temperature fault", "Heater band / thermocouple", "Replaced heater band",
                sym["Barrel zone {n} not reaching setpoint", "Zone {n} thermocouple open alarm", "Nozzle heater cold, short shots"],
                ask["molder zone not heating", "barrel thermocouple open", "nozzle cold short shots"],
                fix["Heater band zone {n} burnt open; replaced band", "Thermocouple zone {n} failed; replaced thermocouple", "Nozzle heater connector burnt; replaced heater and connector"],
                step["Check heater amps", "Check thermocouple", "Replace band", "Verify zone reaches setpoint"],
                part[("IMM-HTR-BD", "Barrel heater band"), ("IMM-TC-J", "Type J thermocouple")]),
            mode!("imm-flash", "Flash on parts", "Clamp tonnage / mold wear", "Adjusted clamp",
                sym["Parts showing flash at parting line", "Flash on cavity {n} after mold change"],
                ask["flash on molded parts", "parting line flash"],
                fix["Clamp tonnage set low after mold change; set to setup sheet value", "Parting line damaged on cavity {n}; sent mold for repair and ran spare"],
                step["Check clamp tonnage", "Inspect parting line", "Clean mold faces"],
                part[("IMM-MLD-SPR", "Mold spare insert")]),
            mode!("imm-hydraulic", "Hydraulic fault", "Oil temp / pump wear", "Repaired hydraulics",
                sym["Hydraulic oil temperature alarm on molder", "Slow clamp movement, pump noisy"],
                ask["molder hydraulic oil hot", "slow clamp noisy pump"],
                fix["Oil cooler water valve closed; opened and flushed cooler", "Hydraulic pump worn; replaced pump"],
                step["Check oil temperature", "Check cooler water flow", "Check pump pressure"],
                part[("IMM-PMP", "Hydraulic pump"), ("IMM-FLT-H", "Hydraulic filter element")]),
        ],
        plans: &[Plan {
            id: "PLN-IMM-M",
            name: "Molder monthly service",
            steps: &[
                "Lockout machine",
                "Check heater bands",
                "Check thermocouples",
                "Replace hydraulic filter",
                "Grease toggle",
                "Test run",
            ],
        }],
    },
    MachineType {
        code: "HSL",
        name: "Heat Sealer",
        weight: 5,
        modes: &[
            mode!("hsl-weak-seal", "Weak seals", "Sealing jaw temperature / pressure", "Adjusted jaws",
                sym["Seals peeling open on packages", "Weak seal on {side} edge, QA rejects"],
                ask["sealer seals weak", "packages not sealing"],
                fix["Jaw heater element failing; replaced element and recalibrated temperature", "Jaw pressure low; reset regulator to 45 psi", "PTFE tape on jaw worn through; replaced tape"],
                step["Check jaw temperature", "Check jaw pressure", "Replace jaw tape", "Seal test"],
                part[("HSL-ELM", "Sealing jaw heater element"), ("HSL-TPE", "PTFE jaw tape")]),
            mode!("hsl-film-track", "Film tracking", "Film guide / tension", "Adjusted film path",
                sym["Film walking off the rollers", "Film wrinkling before the jaws"],
                ask["film tracking off sealer", "film wrinkling"],
                fix["Dancer arm tension spring broken; replaced spring", "Film guide roller bearing seized; replaced roller"],
                step["Check film path", "Check dancer tension", "Inspect rollers"],
                part[("HSL-SPR-D", "Dancer tension spring")]),
        ],
        plans: &[Plan {
            id: "PLN-HSL-W",
            name: "Sealer weekly service",
            steps: &[
                "Lockout sealer",
                "Clean sealing jaws",
                "Inspect jaw tape",
                "Check film rollers",
                "Seal test",
            ],
        }],
    },
    MachineType {
        code: "DLV",
        name: "Dock Leveler",
        weight: 3,
        modes: &[mode!("dlv-no-raise", "Will not raise", "Hydraulic unit fault", "Repaired hydraulic unit",
            sym["Dock leveler will not raise, motor hums", "Leveler lip will not extend at door {n}"],
            ask["dock leveler wont raise", "leveler lip not extending"],
            fix["Hydraulic motor starter failed; replaced starter", "Lip cylinder seal leaking; resealed cylinder and topped off fluid"],
            step["Check hydraulic fluid", "Check motor starter", "Cycle leveler"],
            part[("DLV-STR", "Motor starter"), ("DLV-SKIT", "Lip cylinder seal kit")])],
        plans: &[Plan {
            id: "PLN-DLV-Q",
            name: "Dock leveler quarterly service",
            steps: &["Inspect hinges", "Check hydraulic fluid", "Test lip operation", "Check bumpers"],
        }],
    },
    MachineType {
        code: "LSR",
        name: "Laser Cutter",
        weight: 4,
        modes: &[
            mode!("lsr-power", "Low cut power", "Optics dirty / misaligned", "Cleaned optics",
                sym["Laser not cutting through, low power", "Cut quality poor, dross on bottom edge"],
                ask["laser not cutting through", "dross on laser cuts"],
                fix["Focus lens contaminated; cleaned and replaced protective window", "Beam alignment off; realigned mirrors"],
                step["Inspect focus lens", "Replace protective window", "Check beam alignment", "Test cut"],
                part[("LSR-WIN", "Protective window"), ("LSR-LNS", "Focus lens 5in")]),
            mode!("lsr-coolant", "Coolant alarm", "Coolant flow / temperature", "Restored coolant flow",
                sym["Laser shut down on coolant flow alarm", "Laser coolant temperature high"],
                ask["laser coolant alarm", "laser shutdown coolant flow"],
                fix["Coolant strainer clogged; cleaned strainer and refilled with fresh coolant", "Recirculating pump failing; replaced pump"],
                step["Check coolant level", "Clean strainer", "Check pump flow"],
                part[("LSR-CLT", "Laser coolant 1 gal"), ("LSR-PMP", "Recirculating pump")]),
        ],
        plans: &[Plan {
            id: "PLN-LSR-W",
            name: "Laser weekly service",
            steps: &["Clean focus lens", "Inspect nozzle", "Check coolant", "Empty slag tray", "Test cut"],
        }],
    },
    MachineType {
        code: "SAW",
        name: "Band Saw",
        weight: 3,
        modes: &[mode!("saw-crooked", "Crooked cuts", "Blade tension / guides", "Replaced blade",
            sym["Band saw cutting crooked, blade wandering", "Blade breaking every few days"],
            ask["band saw cutting crooked", "saw blade keeps breaking"],
            fix["Blade guides worn; replaced carbide guides and new blade", "Blade tension low; tensioned to spec and replaced blade"],
            step["Check blade tension", "Inspect guides", "Replace blade", "Test cut"],
            part[("SAW-BLD-1", "Bi-metal blade 1in"), ("SAW-GDE", "Carbide blade guides")])],
        plans: &[Plan {
            id: "PLN-SAW-M",
            name: "Band saw monthly service",
            steps: &["Lockout saw", "Inspect blade", "Check guides", "Clean chip brush", "Check coolant"],
        }],
    },
    MachineType {
        code: "PBT",
        name: "Paint Booth",
        weight: 3,
        modes: &[mode!("pbt-airflow", "Low booth airflow", "Exhaust filters / fan", "Changed filters",
            sym["Paint booth airflow alarm, overspray in room", "Booth manometer reading high"],
            ask["paint booth airflow low", "overspray booth alarm"],
            fix["Exhaust filters loaded; replaced filters", "Exhaust fan belt slipping; replaced belt"],
            step["Check manometer", "Replace exhaust filters", "Inspect exhaust fan"],
            part[("PBT-FLT", "Booth exhaust filter pad"), ("PBT-BLT", "Exhaust fan belt")])],
        plans: &[Plan {
            id: "PLN-PBT-M",
            name: "Paint booth monthly service",
            steps: &[
                "Replace intake filters",
                "Replace exhaust filters",
                "Check manometer",
                "Inspect lights",
                "Clean booth",
            ],
        }],
    },
    MachineType {
        code: "HPR",
        name: "Hydraulic Press",
        weight: 3,
        modes: &[mode!("hpr-leak", "Hydraulic leak", "Hose / cylinder seal", "Replaced hose",
            sym["Hydraulic oil leaking at press cylinder", "Press losing pressure, slow stroke", "Hydraulic hose burst on press"],
            ask["press hydraulic leak", "press losing pressure slow", "hydraulic hose burst"],
            fix["Replaced burst hydraulic hose and cleaned up oil, added hose guard", "Main cylinder seals worn; resealed cylinder", "Relief valve set low; reset to 2200 psi"],
            step["Lockout and bleed hydraulic pressure", "Replace hose", "Check relief setting", "Top off oil"],
            part[("HPR-HOSE-12", "Hydraulic hose 1/2in 4ft"), ("HPR-SKIT", "Cylinder seal kit")])],
        plans: &[Plan {
            id: "PLN-HPR-M",
            name: "Press monthly service",
            steps: &[
                "Lockout and bleed pressure",
                "Inspect hoses",
                "Check oil level and temp",
                "Test light curtains",
                "Check relief valve",
                "Test run",
            ],
        }],
    },
];

/// Fictional technicians.
pub const TECHS: &[&str] = &[
    "A. Rivera",
    "B. Chen",
    "C. Okafor",
    "D. Novak",
    "E. Haddad",
    "F. Lindqvist",
    "G. Patel",
    "H. Moreau",
    "I. Tanaka",
    "J. Ortiz",
    "K. Mensah",
    "L. Kowalski",
    "M. Silva",
    "N. Fischer",
    "O. Adeyemi",
    "P. Ivanova",
];

pub const CREWS: &[&str] = &["mechanical", "electrical", "hvac", "facilities"];

/// Placeholder write-ups that say nothing about what was done.
pub const STUBS: &[&str] = &["done", "completed", "fixed", "see notes", "n/a", "ok"];

pub const CONTEXT: &[&str] = &[
    "Reported by operator:",
    "Called in by supervisor:",
    "Per QA,",
    "{shift} shift:",
    "Third time this week -",
    "",
    "",
    "",
    "During setup",
    "At startup",
];

pub const NOTES: &[&str] = &[
    "Will need follow up at next service",
    "Ordered a spare for stock",
    "Ran 30 min no issues",
    "Told operator to call if it comes back",
    "Root cause likely wear, recommend adding to service plan",
    "Used parts on hand from stock",
    "Needs a planned shutdown for permanent fix",
];

pub const MISC: &[(&str, &str)] = &[
    ("Adjust guard on {side}", "Adjusted guard, tightened bolts"),
    ("Clean up oil on floor near unit", "Cleaned area, no active leak found"),
    ("Install new tool holder", "Installed holder"),
    ("Check noise reported by operator", "Could not duplicate noise, ran 20 min"),
    ("Replace burnt out light in panel", "Replaced lamp"),
    ("Move touchscreen arm for ergonomics", "Moved arm, secured"),
];
